services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photosdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432

  api:
    image: recelos/melanoma-recognizer-api:latest
    depends_on:
      - db
    expose:
      - 8000
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/photosdb    
      - S3_BUCKET_NAME=$S3_BUCKET_NAME
      - S3_ENDPOINT_URL=$S3_ENDPOINT_URL
      - S3_ACCESS_KEY=$S3_ACCESS_KEY
      - S3_SECRET_KEY=$S3_SECRET_KEY
      - S3_REGION=$S3_REGION

  cloudflare:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
volumes:
  db_data:
